### ISSUE TITLE
Meta tags for Facebook sharing on AidCenters' page

### ISSUE THREAD

**Issue by borazslo** [joladnijo/joladnijo-webapp#18]
Amikor egy AidCenter oldalának linkjét megosztjuk a facebookon akkor a fb keres bizonyot tageket a megjelenítéshez. Ezekre figyeljünk.
Infó: https://developers.facebook.com/docs/sharing/webmasters/

Fontos! Ezekben a tag-ekben ne legyen olyan infó ami hamar elavul (konkrét szükségletek / dátum / stb) mert a facebook pharser ritkán dolgozik.

**Comment by borazslo** [comment]
Upsz. Jó próbálkozásnak tűnt, de Facebook Crawler tök mást lát mint a html source a böngészőben. Ami minden bizonnyal tökre evidens NextJS-ben, csak én azt nem ismerem. Szóval most ezt látja a facebook: https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fstaging.joladnijo.hu%2Faid-centers%2Fpiripocs-varoshaza és ez az api-nak tűnik, bár nem értem miért.

**Comment by nvi9** [comment]
> és ez az api-nak tűnik, bár nem értem miért

Szerintem az az oka, hogy a backend url van megadva base path-nak , ami pl. az og:url-be is bekerül.

**Comment by molnarbence** [comment]
Azaz, es pedig eszemben is volt valamikor a heten, aztan tegnap vakon bemergeltem. Hiba volt.
